### ISSUE TITLE
Update embed.js path to use new /static/embed.js route

### ISSUE THREAD

**Issue by kevinfodness** [coralproject/talk-wp-plugin#10]
The old /embed.js route is deprecated, and will be removed in a future version of Coral. Check Coral version when determining embed path, and if >= 4.0.0, use `/static/embed.js`, and if < 4.0.0, use `/embed.js`.

**Comment by kabeaty** [comment]
Hello, I'm closing this, as in `comments-template.php`, we are now checking for the Coral version and using the relevant embed path for each. Thank you!
