### ISSUE TITLE
Stories Section parameters not available 

### ISSUE THREAD

**Issue by alexrothm** [coralproject/talk-wp-plugin#20]
I have deployed Talk v5 via Docker and its running locally but in the story section of the admin-interface the parameters (Title, Author, Publish Date) are not available. (Picture below)

![coral](https://user-images.githubusercontent.com/35106210/68320152-b85bd100-00bf-11ea-96f9-dc976bbad7e7.PNG)

Your help is appreciated!

**Comment by kabeaty** [comment]
Hello, We haven't been able to replicate this issue when taking a look on our end. I recommend checking your scraper settings and if the [scraper](https://github.com/coralproject/talk/blob/develop/server/src/core/server/services/stories/scraper/scraper.ts) is throwing any errors.
