### ISSUE TITLE
Use Canonical URL to create stories

### ISSUE THREAD

**Issue by yogeshbeniwal** [coralproject/talk-wp-plugin#24]
When posts are assigned multiple categories and permalink is set as /%category%/%postname%/, same post is accessible from multiple url, e.g. [Domain]/Category1/post-slug and [Domain]/Category2/Child2/post-slug. This create duplicate stories in Coral for same post.

WordPress use canonical URL to prevent duplicate content error. Coral should prioritise creating stories with canonical URL and merge & show consolidated comments on other URLs.

**Comment by kabeaty** [comment]
Thanks for bringing this up! Closing this issue now, as it's now supported to enable using canonical urls for the story URL for Coral. See https://github.com/coralproject/talk-wp-plugin/releases/tag/v1.0.0
