### ISSUE TITLE
Inputting the Talk Server Base URL with a trailing slash causes the embed URL to break

### ISSUE THREAD

**Issue by jtnelson** [coralproject/talk-wp-plugin#6]
The embed stream doesn't work because it has a double slash `//`

**Comment by joshkadis** [comment]
Hi @jtnelson, sorry I missed this notification. Will take a look. Thanks for reporting!

**Comment by joshkadis** [comment]
@jtnelson Good to go, see `v0.0.6` - thanks for the report!
